language: node_js
sudo: required
node_js:
- node
before_deploy: 
deploy: 
  provider: script
  script: deploy.sh
  on:
    repo: ibm-watson-data-lab/sodashboard
    branch: travis
  skip_cleanup: true

