language: node_js
sudo: required
node_js:
- node
before_install:
- set verbose_script_output "true"
before_deploy: 
- echo "Stand by..."
deploy: 
  provider: script
  script: deploy.sh
  on:
    repo: ibm-watson-data-lab/sodashboard
    branch: travis
  skip_cleanup: true

