language: node_js
sudo: required
node_js:
- node
before_deploy: 
- curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
deploy: 
  provider: script
  script: deploy.sh
  on:
    repo: ibm-watson-data-lab/sodashboard
    branch: travis_test
  skip_cleanup: true
